apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cwln0lgs1-go-gitops
  description: This is GitOps manifest for cwln0lgs1-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: cwln0lgs1-go
    jenkins.io/job-full-name: cwln0lgs1-go-gitops
    backstage.io/kubernetes-id: cwln0lgs1-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:cwln0lgs1-go
